### ISSUE TITLE
Fix wiki 'How to read files'

### ISSUE THREAD

**Issue by IdkGoodName** [Zguy/Jzon#22]
Please fix it, a lot of stuff are missing now. Getting a lot of errors.

**Comment by mankeli** [comment]
Indeed. API seems to have changed. Something like this worked

```
Jzon::Parser pars;
Jzon::Node rootNode = pars.parseFile("test.json");
for (Jzon::Node::iterator it = rootNode.begin(); it != rootNode.end(); ++it) {
...

```

**Comment by mankeli** [comment]
doesn't make sense to close this imo. wiki is still not updated and the snippet i posted is now hidden because the issue is closed. can you reopen or update wiki?
