### ISSUE TITLE
https://github.com/vivkin/jzon

### ISSUE THREAD

**Issue by DBJDBJ** [Zguy/Jzon#24]
https://github.com/vivkin/jzon

I assume this is just an accident?

**Comment by Zguy** [comment]
Your initial commit is 4 years after my initial commit.
Your initial commit is about the same time as my last commit.
You do the math.

**Comment by DBJDBJ** [comment]
AFAIK that project is not my project ...

**Comment by Zguy** [comment]
Okay. Sorry for assuming. I don't understand what you're asking then.

**Comment by Zguy** [comment]
The projects are unrelated and this is the first time I've seen that other one.

**Comment by DBJDBJ** [comment]
Sorted then. Just the same name by accident. Thanks.
